name: Package Manager (Debug)
on:
  pull_request:    
    types: [opened, edited, synchronize, reopened]
    branches:
      - main

  push:
    branches:
      - main

jobs:
  validate:
    runs-on: windows-latest
    outputs:
      changed-files: '${{ steps.validate.outputs.projects }}'     

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - id: validate
        run: |
          . ./scripts/pwsh/_validate-input.ps1 -sha '${{ github.sha }}' -eventname "${{ github.event_name }}" -eventbefore "${{ github.event.before }}" -eventafter "${{ github.event.after }}"
        shell: pwsh

  create-repository:
    needs: validate    
    runs-on: windows-latest
    if: ${{ needs.validate.result == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          '${{ needs.validate.outputs.changed-files }}' | convertfrom-json
        shell: pwsh
        
          # if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.validate.result == 'success' }}
