name: Package Manager
on:
  pull_request:    
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
    paths:
      - repository/*

  push:
    branches:
      - main
    paths:
      - repository/*

jobs:
  create-repository:
    env: 
      GH_TOKEN: ${{ secrets.GH_REPO_MANAGER_TOKEN }}

    runs-on: windows-latest
    if: |
      always() && 
      github.ref == 'refs/heads/main' && 
      github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - id: setup
        run: |
          $baseDirectory = (get-item ".").parent.fullpath
          write-output "base-directory=$baseDirectory" >> $env:GITHUB_OUTPUT
        shell: pwsh      

      - id: validate
        run: |
          . ./scripts/pwsh/_validate-input.ps1 `
              -sha '${{ github.sha }}' `
              -eventname "${{ github.event_name }}" `
              -eventbefore "${{ github.event.before }}" `
              -eventafter "${{ github.event.after }}"
        shell: pwsh

      - name: create
        run: |
          $projects='${{ steps.validate.outputs.changed-files }}' | convertfrom-json

          $projects | foreach-object {
            $project = $_
            write-output "::notice::creating $($project.repository)"
            & ./scripts/pwsh/_clone-template.ps1 -project:$project  
            write-output "::notice::created $($project.repository)"        
          }
        shell: pwsh
        working-directory: ${{ steps.setup.outputs.base-directory }}
